services:
  - type: web
    name: shellquest-web
    rootDir: web
    env: node
    branch: main
    plan: standard
    region: oregon
    buildCommand: |
      pnpm install
      pnpm prisma-generate 
      pnpm build
#    domains:
#      - shellquest.sh
    startCommand: pnpm serve
    autoDeploy: true
    envVars:
      - key: DATABASE_URL    # inject DB connection string at deploy time
        fromDatabase:
          name: shellquest-db       # must match the database name below
          property: connectionString
  - type: web
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    rootDir: web
    name: shellquest-web-static
#    domain: static.shellquest.sh
    runtime: static
    buildCommand: |
      pnpm install
      pnpm prisma-generate 
      pnpm build:client
    staticPublishPath: ./dist/app/client

databases:
  - name: shellquest-db
    databaseName: shellquest
    user: app_user
    plan: basic-256mb
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

